trigger:
  - main

jobs:
  - job: Build
    steps:
    - script: |
        npm install -g npm-audit-html
      displayName: "CLI tools install"
    - task: Npm@1
      displayName: "Audit Application"
      continueOnError: true
      inputs:
        workingDir: $(System.DefaultWorkingDirectory)
        command: custom
        customCommand: "audit --registry=https://registry.npmjs.org/"
    - script: |
        npm audit --registry=https://registry.npmjs.org/ --json | npm-audit-html --output $(System.DefaultWorkingDirectory)/npm-audit-report/report.html
      displayName: "Generate audit report"
      continueOnError: true
    - task: PublishPipelineArtifact@1
      continueOnError: true
      inputs:
        targetPath: "$(System.DefaultWorkingDirectory)/npm-audit-report"
        artifact: "npm-audit-report"
        publishLocation: "pipeline"
    - task: Npm@1
      displayName: "Package install"
      inputs:
        command: 'install'
        workingDir: $(System.DefaultWorkingDirectory)
        verbose: true
    - task: Npm@1
      displayName: "Unit test"
      inputs:
        command: 'custom'
        workingDir: $(System.DefaultWorkingDirectory)
        customCommand: 'test'
    - task: PublishTestResults@2
      displayName: "Task test publishing"
      continueOnError: true
      condition: succeededOrFailed()
      inputs:
        testResultsFormat: "JUnit"
        testResultsFiles: "test-outputs/test-junit-*.xml"
        mergeTestResults: true
        failTaskOnFailedTests: false
        testRunTitle: "Test Results"
    - task: Npm@1
      displayName: "Build"
      inputs:
        command: 'custom'
        workingDir: $(System.DefaultWorkingDirectory)
        customCommand: 'run build'